"""
Patch 200 — PWA-Assets für Nala und Hel.

Liefert pro App ein eigenes Manifest und einen eigenen Service Worker, jeweils
ohne Auth (Hel-Router-Auth gilt nur für die /hel-Endpunkte des Hel-Routers,
nicht für die hier registrierten Pfade unter demselben Prefix — der PWA-Router
muss dafür VOR dem Hel-Router in main.py eingehängt werden).

Endpoints (alle public, keine Basic-Auth, kein JWT):
  GET /nala/manifest.json
  GET /nala/sw.js
  GET /hel/manifest.json
  GET /hel/sw.js

Architektur:
- Manifest-Dicts sind Pure-Python-Konstanten — testbar ohne TestClient.
- Service-Worker-Quelltext wird per Template gerendert (cache_name + shell-Liste).
- Scope des Service Workers ergibt sich aus dem Pfad, von dem aus er
  ausgeliefert wird (/nala/sw.js → scope /nala/, /hel/sw.js → scope /hel/).
  Damit kein `Service-Worker-Allowed`-Header nötig.
- Icons liegen unter /static/pwa/<app>-<size>.png (öffentlich via StaticFiles).
"""
from __future__ import annotations

import json
from pathlib import Path

from fastapi import APIRouter
from fastapi.responses import JSONResponse, Response


router = APIRouter(tags=["PWA"])


# ---------------------------------------------------------------------------
# Manifest-Definitionen
# ---------------------------------------------------------------------------

NALA_MANIFEST: dict = {
    "name": "Nala – Der Palast",
    "short_name": "Nala",
    "description": "Nala-Chat (Zerberus)",
    "start_url": "/nala/",
    "scope": "/nala/",
    "display": "standalone",
    "orientation": "portrait",
    "theme_color": "#0a1628",
    "background_color": "#0a1628",
    "lang": "de",
    "icons": [
        {
            "src": "/static/pwa/nala-192.png",
            "sizes": "192x192",
            "type": "image/png",
            "purpose": "any maskable",
        },
        {
            "src": "/static/pwa/nala-512.png",
            "sizes": "512x512",
            "type": "image/png",
            "purpose": "any maskable",
        },
    ],
}

HEL_MANIFEST: dict = {
    "name": "Hel – Zerberus Admin",
    "short_name": "Hel",
    "description": "Zerberus Admin-Konsole",
    "start_url": "/hel/",
    "scope": "/hel/",
    "display": "standalone",
    "orientation": "any",
    "theme_color": "#1a1a1a",
    "background_color": "#1a1a1a",
    "lang": "de",
    "icons": [
        {
            "src": "/static/pwa/hel-192.png",
            "sizes": "192x192",
            "type": "image/png",
            "purpose": "any maskable",
        },
        {
            "src": "/static/pwa/hel-512.png",
            "sizes": "512x512",
            "type": "image/png",
            "purpose": "any maskable",
        },
    ],
}


# ---------------------------------------------------------------------------
# Service-Worker-Template
# ---------------------------------------------------------------------------
#
# App-Shell-Caching:
#   - install: precache der angegebenen Shell-URLs
#   - activate: alte Caches mit anderem Versionsschlüssel räumen
#   - fetch:   network-first für GETs, fallback auf Cache; non-GET passt durch
#
# Bewusst minimal — keine Push-Notifications, kein Background-Sync,
# kein Offline-Modus für POST/SSE (Server muss eh laufen).

SW_TEMPLATE = """// Auto-generated by zerberus.app.routers.pwa — do not edit.
const CACHE_NAME = {cache_name!r};
const APP_SHELL = {shell!s};

self.addEventListener('install', (event) => {{
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(APP_SHELL)).catch(() => null)
  );
  self.skipWaiting();
}});

self.addEventListener('activate', (event) => {{
  event.waitUntil(
    caches.keys().then((keys) => Promise.all(
      keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k))
    ))
  );
  self.clients.claim();
}});

self.addEventListener('fetch', (event) => {{
  if (event.request.method !== 'GET') return;
  event.respondWith(
    fetch(event.request).then((res) => {{
      if (res && res.ok && res.type === 'basic') {{
        const copy = res.clone();
        caches.open(CACHE_NAME).then((cache) => cache.put(event.request, copy)).catch(() => null);
      }}
      return res;
    }}).catch(() => caches.match(event.request).then((cached) => cached || Response.error()))
  );
}});
"""


NALA_SHELL: list[str] = [
    "/nala/",
    "/static/css/shared-design.css",
    "/static/favicon.ico",
    "/static/pwa/nala-192.png",
    "/static/pwa/nala-512.png",
]

HEL_SHELL: list[str] = [
    "/hel/",
    "/static/css/shared-design.css",
    "/static/favicon.ico",
    "/static/pwa/hel-192.png",
    "/static/pwa/hel-512.png",
]


def render_service_worker(cache_name: str, shell: list[str]) -> str:
    """Pure-Function: rendert SW-Quelltext aus Cache-Name + Shell-Liste."""
    shell_json = json.dumps(list(shell))
    return SW_TEMPLATE.format(cache_name=cache_name, shell=shell_json)


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@router.get("/nala/manifest.json")
async def nala_manifest() -> JSONResponse:
    return JSONResponse(
        NALA_MANIFEST,
        media_type="application/manifest+json",
    )


@router.get("/hel/manifest.json")
async def hel_manifest() -> JSONResponse:
    return JSONResponse(
        HEL_MANIFEST,
        media_type="application/manifest+json",
    )


@router.get("/nala/sw.js")
async def nala_service_worker() -> Response:
    body = render_service_worker("nala-shell-v1", NALA_SHELL)
    return Response(
        content=body,
        media_type="application/javascript",
        headers={"Cache-Control": "no-cache"},
    )


@router.get("/hel/sw.js")
async def hel_service_worker() -> Response:
    body = render_service_worker("hel-shell-v1", HEL_SHELL)
    return Response(
        content=body,
        media_type="application/javascript",
        headers={"Cache-Control": "no-cache"},
    )


# Pfad zu den Icons im Repo (für Source-Audit-Tests)
PWA_ICONS_DIR = Path("zerberus") / "static" / "pwa"
